### PR TITLE
Fix list sort

### LINKED ISSUE #27: Sorting reports by layers
In the report list :
- display the layer used for the report
- sort by layer
- filter by layer

### PR DESCRIPTION
**Pull request by golbian**
Add sorting By layerName.

Fixes #27

### CODE REVIEW

File: migrations/20190410101237-fix-localField-type.js [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+                }
+
+            });
+        });
+
+        db.collection('wst_Reports').bulkWrite(operations);
+    },
+
+    down (db) {
+    }
```
Comment (jajm) [inline migrations/20190410101237-fix-localField-type.js]: It is possible to rollback the migration here, so you must also write the "down" part

File: server/core/controller.js [hunk 2]
```diff
@@ -7,6 +7,32 @@ class Controller {
         var Model = this.model;
         var perPage = config.get('pagination.itemsPerPage');
         var page = (req.query.page) ? req.query.page : 1;
+
+        var component = this.findAllComponent(req);
```
Comment (jajm) [inline server/core/controller.js]: `findAllComponent` is confusing as a function name. It does not describe what the function does. Can you try to find a better name ?

File: server/core/controller.js [hunk 3]
```diff
@@ -19,6 +45,10 @@ class Controller {
 
             sortField[req.query.sort] = (req.query.sortType) ? req.query.sortType : 1;
 
+            var int = Number(sortField[req.query.sort]);
+
+            sortField[req.query.sort] = int;
```
Comment (jajm) [inline server/core/controller.js]: You can merge those two lines into:

```js
sortField[req.query.sort] = Number(sortField[req.query.sort]);
```

It is still readable and avoids having a badly named temporary variable.

File: server/custom/reports/controller.js [hunk 4]
```diff
@@ -17,8 +17,73 @@ exports.ReportsFindAll = async function (req, res) {
...
+    if (req.query.populate === 'layer') {
+        var aggregation = Reports.aggregate([
+            {
+                $lookup:
+        {
+            from: 'wst_Layers',
+            localField: 'selectedLayerID',
+            foreignField: '_id',
+            as: 'layer'
+        }
```
Comment (jajm) [inline server/custom/reports/controller.js]: Please fix indentation.
Ideally, a value should start on the same line as the property:

```js
$lookup: {
    // ...
}
```

File: server/custom/reports/controller.js [hunk 5]
```diff
@@ -17,8 +17,73 @@ exports.ReportsFindAll = async function (req, res) {
...
+
+            },
+            {
+                $unwind:
+     {
+         path: '$layer',
+     }
```
Comment (jajm) [inline server/custom/reports/controller.js]: Please fix indentation

File: server/custom/reports/controller.js [hunk 6]
```diff
@@ -17,8 +17,73 @@ exports.ReportsFindAll = async function (req, res) {
...
+            },
+            {
+                $match: result.find,
+            },
+            {
+                $project: {
+                    'result.fields': 1,
```
Comment (jajm) [inline server/custom/reports/controller.js]: There is no `result.fields` field inside a report. This line is useless.

File: server/custom/reports/controller.js [hunk 7]
```diff
@@ -17,8 +17,73 @@ exports.ReportsFindAll = async function (req, res) {
...
+                    author: 1,
+                    createdBy: 1,
+                    createdOn: 1,
+                    companyID: 1,
+                    nd_trash_deleted: 1,
+                    history: 1,
+                    __v: 1,
+                    isPublic: 1,
+                    layerName: '$layer.name'
+                }
```
Comment (jajm) [inline server/custom/reports/controller.js]: Are all these fields really needed ? Is `__v` used anywhere for instance ?

You should probably fetch only fields listed in `result.fields` (that comes from `findAllComponent`) + `layerName`

File: server/custom/reports/model.js [hunk 8]
```diff
@@ -5,6 +5,7 @@ var ReportsSchema = new mongoose.Schema({
     reportName: {type: String, required: true},
     reportType: {type: String},
     reportDescription: {type: String},
+    layerName: {type: String},
```
Comment (jajm) [inline server/custom/reports/model.js]: No new field should be added to the schema

File: server/custom/reports/model.js [hunk 9]
```diff
@@ -17,7 +18,7 @@ var ReportsSchema = new mongoose.Schema({
     isPublic: {type: Boolean},
     nd_trash_deleted: {type: Boolean},
     nd_trash_deleted_date: {type: Date},
-    selectedLayerID: {type: String}
+    selectedLayerID: {type: Object, ref: 'Layers'}
```
Comment (jajm) [inline server/custom/reports/model.js]: It's not an `Object`, it's an `ObjectId`

https://mongoosejs.com/docs/schematypes.html#objectids

Comment (jajm) [reply server/custom/reports/model.js]: and `ref` is only needed for population, which is not used.

File: migrations/20190410101237-fix-localField-type.js [hunk 10]
```diff
@@ -0,0 +1,25 @@
...
+                    'filter': {'_id': report._id},
+                    'update': {
+                        '$set': {'selectedLayerID': ObjectID(layerID)}
+                    }
+                }
+
+            });
+        });
+
+        db.collection('wst_Reports').bulkWrite(operations);
```
Comment (jajm) [inline migrations/20190410101237-fix-localField-type.js]: bulkWrite returns a Promise.
It should be returned by `up` so that migrate-mongo know when the bulkWrite is finished.

Comment (jajm) [reply migrations/20190410101237-fix-localField-type.js]: The migration fails if there is no reports in mongo database.

```
UnhandledPromiseRejectionWarning: MongoError: Invalid Operation, no operations specified
    at Function.create (/home/urungi/urungi/node_modules/migrate-mongo/node_modules/mongodb-core/lib/error.js:43:12)
    at toError (/home/urungi/urungi/node_modules/migrate-mongo/node_modules/mongodb/lib/utils.js:149:22)
    at OrderedBulkOperation.bulkExecute (/home/urungi/urungi/node_modules/migrate-mongo/node_modules/mongodb/lib/bulk/common.js:937:31)
    at OrderedBulkOperation.execute (/home/urungi/urungi/node_modules/migrate-mongo/node_modules/mongodb/lib/bulk/ordered.js:117:22)
    at bulkWrite (/home/urungi/urungi/node_modules/migrate-mongo/node_modules/mongodb/lib/operations/collection_ops.js:115:8)
    at /home/urungi/urungi/node_modules/migrate-mongo/node_modules/mongodb/lib/utils.js:437:24
    at new Promise (<anonymous>)
    at executeOperation (/home/urungi/urungi/node_modules/migrate-mongo/node_modules/mongodb/lib/utils.js:432:10)
    at Collection.bulkWrite (/home/urungi/urungi/node_modules/migrate-mongo/node_modules/mongodb/lib/collection.js:595:10)
    at up (/home/urungi/urungi/migrations/20190410101237-fix-localField-type.js:21:38)
```

You should not call `bulkWrite` if `operations` is empty

File: server/custom/reports/model.js (hunk 9 above)
Comment (jajm) [reply server/custom/reports/model.js]: Probably related: when I save a report, selectedLayerId is saved as a string instead of an object id, and it does not appear on the reports page
